GRANT EXECUTE ON UTL_FILE TO SYS;

CREATE OR REPLACE DIRECTORY DATASETS_2019 AS 'C:\Users\Watanabe\Desktop\Repositorios\StackOverflowRelatory\datasets\2019';
CREATE OR REPLACE DIRECTORY DATASETS_2023 AS 'C:\Users\Watanabe\Desktop\Repositorios\StackOverflowRelatory\datasets\2023';

GRANT READ ON DIRECTORY DATASETS_2019 TO SYS;
GRANT READ ON DIRECTORY DATASETS_2023 TO SYS;

SELECT * FROM ALL_DIRECTORIES WHERE DIRECTORY_NAME LIKE '%DATASETS%';
SELECT * FROM ALL_TAB_PRIVS;

COMMIT;
